In [1]:
import pandas as pd
import numpy as np
import os
import glob
from cleaning_script import adaptive_clean_real_estate_data
from feature_engineering import build_features

In [26]:
#GOING BACK AND LOOKING AT THE RAW DATASETS
data_dir = '../original_datasets'

# Pattern to match all CRMLS monthly files
pattern = os.path.join(data_dir, "CRMLSSold2025??_filled.csv")

# Get all matching file paths
file_list = sorted(glob.glob(pattern))

print("Files found:", file_list)

# Load and store each DataFrame
dfs = []
for f in file_list:
    df = pd.read_csv(f, low_memory=False)
    dfs.append(df)

# Merge vertically (stack rows)
merged_df = pd.concat(dfs, ignore_index=True)

print("Merged shape:", merged_df.shape)

Files found: ['../original_datasets\\CRMLSSold202502_filled.csv', '../original_datasets\\CRMLSSold202503_filled.csv', '../original_datasets\\CRMLSSold202504_filled.csv', '../original_datasets\\CRMLSSold202505_filled.csv', '../original_datasets\\CRMLSSold202506_filled.csv', '../original_datasets\\CRMLSSold202507_filled.csv']
Merged shape: (133092, 80)

In [27]:
aug = pd.read_csv('../original_datasets/CRMLSSold202508_filled-2.csv')
sept = pd.read_csv('../original_datasets/CRMLSSold202509.csv')
merged_df

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,RanchoSoutheast,RanchoSoutheast,NaN,True,NaN,NaN,NaN,60000.0,526199946,cmark1018@yahoo.com,...,NaN,False,NaN,NaN,92307,0.0,28000.0,NaN,False,False
1,InlandValleys,InlandValleys,NaN,False,NaN,NaN,NaN,550000.0,525585060,mozcorona@aol.com,...,NaN,False,NaN,NaN,92553,0.0,39640.0,NaN,False,False
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,880000.0,497696903,lenskab@gmail.com,...,NaN,False,2.0,NaN,91942,NaN,NaN,NaN,False,False
3,SanDiego,SanDiego,NaN,False,NaN,NaN,False,875000.0,497696407,lenskab@gmail.com,...,NaN,False,2.0,NaN,91942,NaN,NaN,NaN,False,False
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,849000.0,486616176,lenskab@gmail.com,...,NaN,False,2.0,NaN,91942,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133087,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,7750000.0,1022700795,adam@OCcollective.com,...,NaN,False,NaN,NaN,92154,0.0,243065.0,NaN,False,False
133088,CaliforniaDesert,CaliforniaDesert,"Carpet,Tile",True,NaN,NaN,True,5800.0,1020000387,avi@unigrafix.com,...,NaN,False,2.0,NaN,92270,775.0,5227.0,NaN,False,False
133089,Glendale,Glendale,NaN,NaN,NaN,NaN,NaN,13850000.0,1019043037,Listings@LockerRealty.com,...,NaN,NaN,NaN,NaN,90277,NaN,68003.0,NaN,False,False
133090,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,2500000.0,1018313206,drew@teicheirateam.com,...,NaN,False,NaN,NaN,91730,0.0,1310720.0,NaN,False,False
133091,MariposaCounty,MariposaCounty,NaN,True,NaN,NaN,NaN,240000.0,1006166259,patti@sierrafoothillhomes.net,...,NaN,False,NaN,NaN,95338,0.0,1767229.0,NaN,False,False

In [28]:
merged_df = pd.concat([merged_df, aug, sept], ignore_index=True)
merged_df.shape

(178507, 80)

In [29]:
merged_df = merged_df[(merged_df['PropertyType']=='Residential') & (merged_df['PropertySubType']=='SingleFamilyResidence')]

In [30]:
merged_df.to_csv('combined_raw_data.csv', index=False)

In [31]:
testing_set = pd.read_csv('../original_datasets/CRMLSSold202510.csv')
testing_set.to_csv('testing_raw_data.csv', index=False)

In [ ]:
train_cleaned, stats, mechs = adaptive_clean_real_estate_data(merged_df, fit = True)
test_clean, _, _ = adaptive_clean_real_estate_data(testing_set, fit = False, imputation_stats=stats, missing_mechanisms=mechs, trim_outliers=True)

================================================================================
ADAPTIVE CLEANING - TRAINING DATA
================================================================================
Initial shape: (89843, 81)

Dropping 21 columns with >75% missing

================================================================================
DIAGNOSING MISSING DATA MECHANISMS
================================================================================

ViewYN: NMAR (amenity - missing likely means absent)

PoolPrivateYN: NMAR (amenity - missing likely means absent)

AttachedGarageYN: NMAR (amenity - missing likely means absent)

LotSizeAcres: MAR detected (correlates with 1 features)
  - Latitude: r=-0.135

BathroomsTotalInteger: MAR detected (correlates with 1 features)
  - LotSizeSquareFeet: r=0.104

FireplaceYN: NMAR (amenity - missing likely means absent)

Stories: MAR detected (correlates with 3 features)
  - Latitude: r=0.299
  - Longitude: r=-0.220
  - BathroomsTotalInteger: r=0.100

LotSizeArea: MAR detected (correlates with 1 features)
  - Latitude: r=-0.136

GarageSpaces: MAR detected (correlates with 1 features)
  - YearBuilt: r=-0.147

LotSizeSquareFeet: MAR detected (correlates with 2 features)
  - Latitude: r=-0.135
  - LotSizeAcres: r=0.871

--------------------------------------------------------------------------------
MECHANISM SUMMARY:
  MCAR: 10 columns
  MAR:  6 columns
  NMAR: 4 columns

================================================================================
ADAPTIVE IMPUTATION
================================================================================

ViewYN (NMAR): Created missing indicator, filled with False

PoolPrivateYN (NMAR): Created missing indicator, filled with False

Latitude (MCAR): Filled with 34.08

Longitude (MCAR): Filled with -118.03

LivingArea (MCAR): Filled with 1812.00

AttachedGarageYN (NMAR): Created missing indicator, filled with False

ParkingTotal (MCAR): Filled with 0.00

LotSizeAcres (MAR): Will use model-based imputation

YearBuilt (MCAR): Filled with 1976.00

BathroomsTotalInteger (MAR): Will use model-based imputation

FireplaceYN (NMAR): Created missing indicator, filled with False

Stories (MAR): Will use model-based imputation

LotSizeArea (MAR): Will use model-based imputation

GarageSpaces (MAR): Will use model-based imputation

LotSizeSquareFeet (MAR): Will use model-based imputation

--------------------------------------------------------------------------------
Applying IterativeImputer to 6 MAR numeric features...
  ✓ Fitted IterativeImputer

⚠️  Remaining nulls: {'City': 57, 'PurchaseContractDate': 4, 'PostalCode': 1, 'SourceFile': 22908}

================================================================================
CLEANING COMPLETE
================================================================================
Final shape: (66871, 31)
Rows retained: 66871/89843 (74.4%)

Missingness indicators created: 4
  - ViewYN_was_missing: 9.2% of data
  - PoolPrivateYN_was_missing: 7.9% of data
  - AttachedGarageYN_was_missing: 11.9% of data
  - FireplaceYN_was_missing: 0.1% of data
================================================================================
================================================================================
ADAPTIVE CLEANING - TEST DATA
================================================================================
Initial shape: (23233, 78)

Dropping 20 columns with >75% missing

================================================================================
ADAPTIVE IMPUTATION
================================================================================

ViewYN (NMAR): Created missing indicator, filled with False

PoolPrivateYN (NMAR): Created missing indicator, filled with False

Latitude (MCAR): Filled with 34.08

Longitude (MCAR): Filled with -118.03

LivingArea (MCAR): Filled with 1812.00

AttachedGarageYN (NMAR): Created missing indicator, filled with False

LotSizeAcres (MAR): Will use model-based imputation

YearBuilt (MCAR): Filled with 1976.00

FireplaceYN (NMAR): Created missing indicator, filled with False

Stories (MAR): Will use model-based imputation

LotSizeArea (MAR): Will use model-based imputation

GarageSpaces (MAR): Will use model-based imputation

LotSizeSquareFeet (MAR): Will use model-based imputation

--------------------------------------------------------------------------------
Applying IterativeImputer to 6 MAR numeric features...
  ✓ Applied IterativeImputer

⚠️  Remaining nulls: {'CoListOfficeName': 6991, 'PurchaseContractDate': 2}

================================================================================
CLEANING COMPLETE
================================================================================
Final shape: (4916, 31)
Rows retained: 4916/23233 (21.2%)

Missingness indicators created: 4
  - ViewYN_was_missing: 6.1% of data
  - PoolPrivateYN_was_missing: 9.2% of data
  - AttachedGarageYN_was_missing: 14.3% of data
  - FireplaceYN_was_missing: 0.1% of data
================================================================================

In [23]:
train_cleaned.to_csv('train_cleaned.csv', index=False)
test_clean.to_csv('test_cleaned.csv', index=False)

GOAL: BRAINSTORM NEIGHBORHOOD LEVEL FEATURES

In [19]:
train_with_features, test_with_features = build_features(train_cleaned, test_clean)

Building features...
  - Temporal features
  - Log transforms and age buckets
  - Ratio features
  - Boolean interactions
  - Coastal distance
  - Geographic clustering
  - Target encoding (k-fold)
  - Local pricing benchmarks
  - Market velocity indicators
  - Cleanup
✓ Feature engineering complete
  Train: (66871, 60)
  Test:  (4916, 60)
  ⚠️  Warning: Categorical columns in train: ['SourceFile']
  ⚠️  Warning: Categorical columns in test: ['CoListOfficeName']

In [20]:
train_with_features

,ViewYN,PoolPrivateYN,ClosePrice,Latitude,Longitude,LivingArea,AttachedGarageYN,ParkingTotal,LotSizeAcres,YearBuilt,...,IsCoastal,GeoCluster,City_TE,PostalCode_TE,CountyOrParish_TE,ZIP_MedianPPSF,City_MedianPPSF,County_MedianPPSF,ZIP_SalesCount,ZIP_MedianDOM
2,False,False,875000.0,32.765380,-117.043486,2340.0,True,6.0,10.335832,2021.0,...,0,7,4.655753e+06,9.117890e+05,1.658581e+06,639.820548,603.876289,605.345912,12,82.5
3,False,False,875000.0,32.765038,-117.043568,2165.0,True,4.0,10.250255,2021.0,...,0,7,4.882246e+06,9.023506e+05,1.679895e+06,639.820548,603.876289,605.345912,12,82.5
4,False,False,849000.0,32.765031,-117.043252,2158.0,True,4.0,10.248912,2021.0,...,0,7,1.014663e+06,9.060148e+05,1.568255e+06,639.820548,603.876289,605.345912,12,82.5
15,True,False,1100000.0,33.724000,-118.294924,2545.0,False,3.0,0.103300,1962.0,...,0,0,1.087204e+06,9.945915e+05,1.540484e+06,669.701987,658.866995,645.624103,15,51.0
16,False,False,760000.0,37.687556,-122.150114,1692.0,True,2.0,0.115700,1950.0,...,0,1,9.222381e+05,9.349555e+05,1.463035e+06,659.484938,638.103920,765.172861,9,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133047,True,True,2625000.0,33.602236,-116.147017,7513.0,True,10.0,0.320000,2019.0,...,0,11,4.280677e+05,4.280677e+05,7.793481e+05,227.715877,227.715877,323.834197,6,177.0
133062,True,False,375000.0,34.118035,-116.428352,1770.0,True,2.0,0.095200,2022.0,...,0,11,4.300089e+05,4.298940e+05,6.103156e+05,254.922942,254.355401,328.194005,49,91.0
133068,True,False,1980000.0,39.357862,-123.821861,4700.0,False,6.0,0.560000,1979.0,...,0,18,1.531056e+06,1.531056e+06,8.604704e+05,514.904687,514.904687,454.480146,4,343.5
133073,True,False,550000.0,34.481528,-117.266840,3045.0,True,2.0,0.165300,1990.0,...,0,17,4.440091e+05,4.367601e+05,6.082315e+05,257.308762,244.097565,328.194005,33,80.0
133081,True,False,110000000.0,34.073330,-118.428287,56500.0,False,0.0,4.601700,1990.0,...,1,0,2.062841e+06,4.191833e+06,1.516149e+06,1273.100870,850.762141,645.624103,8,48.0

import model_training

In [2]:
import model_training

c:\Users\jueeh\idx-exchange-ds34\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
model, metrics = model_training.main()

XGBOOST REAL ESTATE PRICE PREDICTION PIPELINE
Loading data...
================================================================================
ADAPTIVE CLEANING - TRAINING DATA
================================================================================
Initial shape: (89843, 80)

Dropping 21 columns with >75% missing

================================================================================
DIAGNOSING MISSING DATA MECHANISMS
================================================================================

ViewYN: NMAR (amenity - missing likely means absent)

PoolPrivateYN: NMAR (amenity - missing likely means absent)

AttachedGarageYN: NMAR (amenity - missing likely means absent)

LotSizeAcres: MAR detected (correlates with 1 features)
  - Latitude: r=-0.135

BathroomsTotalInteger: MAR detected (correlates with 1 features)
  - LotSizeSquareFeet: r=0.104

FireplaceYN: NMAR (amenity - missing likely means absent)

Stories: MAR detected (correlates with 3 features)
  - Latitude: r=0.299
  - Longitude: r=-0.220
  - BathroomsTotalInteger: r=0.100

LotSizeArea: MAR detected (correlates with 1 features)
  - Latitude: r=-0.136

GarageSpaces: MAR detected (correlates with 1 features)
  - YearBuilt: r=-0.147

LotSizeSquareFeet: MAR detected (correlates with 2 features)
  - Latitude: r=-0.135
  - LotSizeAcres: r=0.871

--------------------------------------------------------------------------------
MECHANISM SUMMARY:
  MCAR: 9 columns
  MAR:  6 columns
  NMAR: 4 columns

================================================================================
ADAPTIVE IMPUTATION
================================================================================

ViewYN (NMAR): Created missing indicator, filled with False

PoolPrivateYN (NMAR): Created missing indicator, filled with False

Latitude (MCAR): Filled with 34.08

Longitude (MCAR): Filled with -118.03

LivingArea (MCAR): Filled with 1812.00

AttachedGarageYN (NMAR): Created missing indicator, filled with False

ParkingTotal (MCAR): Filled with 0.00

LotSizeAcres (MAR): Will use model-based imputation

YearBuilt (MCAR): Filled with 1976.00

BathroomsTotalInteger (MAR): Will use model-based imputation

FireplaceYN (NMAR): Created missing indicator, filled with False

Stories (MAR): Will use model-based imputation

LotSizeArea (MAR): Will use model-based imputation

GarageSpaces (MAR): Will use model-based imputation

LotSizeSquareFeet (MAR): Will use model-based imputation

--------------------------------------------------------------------------------
Applying IterativeImputer to 6 MAR numeric features...
  ✓ Fitted IterativeImputer

⚠️  Remaining nulls: {'City': 57, 'PurchaseContractDate': 4, 'PostalCode': 1}

================================================================================
CLEANING COMPLETE
================================================================================
Final shape: (89775, 30)
Rows retained: 89775/89843 (99.9%)

Missingness indicators created: 4
  - ViewYN_was_missing: 9.2% of data
  - PoolPrivateYN_was_missing: 7.8% of data
  - AttachedGarageYN_was_missing: 12.0% of data
  - FireplaceYN_was_missing: 0.1% of data
================================================================================
================================================================================
ADAPTIVE CLEANING - TEST DATA
================================================================================
Initial shape: (23233, 78)

Dropping 20 columns with >75% missing

================================================================================
ADAPTIVE IMPUTATION
================================================================================

ViewYN (NMAR): Created missing indicator, filled with False

PoolPrivateYN (NMAR): Created missing indicator, filled with False

Latitude (MCAR): Filled with 34.08

Longitude (MCAR): Filled with -118.03

LivingArea (MCAR): Filled with 1812.00

AttachedGarageYN (NMAR): Created missing indicator, filled with False

LotSizeAcres (MAR): Will use model-based imputation

YearBuilt (MCAR): Filled with 1976.00

FireplaceYN (NMAR): Created missing indicator, filled with False

Stories (MAR): Will use model-based imputation

LotSizeArea (MAR): Will use model-based imputation

GarageSpaces (MAR): Will use model-based imputation

LotSizeSquareFeet (MAR): Will use model-based imputation

--------------------------------------------------------------------------------
Applying IterativeImputer to 6 MAR numeric features...
  ✓ Applied IterativeImputer

⚠️  Remaining nulls: {'PurchaseContractDate': 2}

================================================================================
CLEANING COMPLETE
================================================================================
Final shape: (11905, 30)
Rows retained: 11905/23233 (51.2%)

Missingness indicators created: 4
  - ViewYN_was_missing: 10.0% of data
  - PoolPrivateYN_was_missing: 7.6% of data
  - AttachedGarageYN_was_missing: 11.5% of data
  - FireplaceYN_was_missing: 0.1% of data
================================================================================
  Train: (89775, 30)
  Test:  (11905, 30)

Building features...
Building features...
  - Temporal features
  - Log transforms and age buckets
  - Ratio features
  - Boolean interactions
  - Coastal distance
  - Geographic clustering
  - Target encoding (k-fold)
  - Local pricing benchmarks
  - Market velocity indicators

[I 2025-11-25 14:19:21,533] A new study created in memory with name: no-name-a9acc7b1-bbdc-469e-8703-e254970050b8

  - Cleanup
✓ Feature engineering complete
  Train: (89775, 59)
  Test:  (11905, 59)
  Train shape after feature engineering: (89775, 59)
  Test shape after feature engineering:  (11905, 59)
  ✓ All features are numeric

Final shapes:
  X_train: (89775, 58)
  y_train: (89775,)
  X_test:  (11905, 58)
  ✓ Feature alignment verified: 58 features

============================================================
HYPERPARAMETER TUNING (40 trials, 3-fold CV)
============================================================

Best trial: 0. Best value: -0.0719286:   2%|▎         | 1/40 [00:10<06:38, 10.21s/it]

[I 2025-11-25 14:19:31,742] Trial 0 finished with value: -0.0719285938286703 and parameters: {'n_estimators': 1005, 'learning_rate': 0.015996747560492682, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.6464485640585839, 'colsample_bytree': 0.8966709871805307, 'gamma': 2.586679419679114, 'reg_alpha': 1.116105598008624, 'reg_lambda': 2.8756851154283174}. Best is trial 0 with value: -0.0719285938286703.

Best trial: 0. Best value: -0.0719286:   5%|▌         | 2/40 [00:18<05:41,  8.99s/it]

[I 2025-11-25 14:19:39,873] Trial 1 finished with value: -0.10741378455822244 and parameters: {'n_estimators': 695, 'learning_rate': 0.07164773450633226, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.9486838822638374, 'colsample_bytree': 0.772922712737081, 'gamma': 4.473862483460612, 'reg_alpha': 1.403720081377815, 'reg_lambda': 2.075839809539126}. Best is trial 0 with value: -0.0719285938286703.

Best trial: 0. Best value: -0.0719286:   8%|▊         | 3/40 [00:31<06:43, 10.90s/it]

[I 2025-11-25 14:19:53,045] Trial 2 finished with value: -0.1726121628474754 and parameters: {'n_estimators': 1378, 'learning_rate': 0.07564079111534801, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.7573883010627005, 'colsample_bytree': 0.8602231024006497, 'gamma': 1.2167354403587334, 'reg_alpha': 2.152457349363123, 'reg_lambda': 1.1878975111382952}. Best is trial 0 with value: -0.0719285938286703.

Best trial: 0. Best value: -0.0719286:  10%|█         | 4/40 [00:49<08:18, 13.84s/it]

[I 2025-11-25 14:20:11,389] Trial 3 finished with value: -0.10963131548963201 and parameters: {'n_estimators': 913, 'learning_rate': 0.023846332611708734, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.692201192850519, 'colsample_bytree': 0.6431807220705242, 'gamma': 3.1270728270912307, 'reg_alpha': 0.12356288280604533, 'reg_lambda': 0.8830251943526964}. Best is trial 0 with value: -0.0719285938286703.

Best trial: 4. Best value: -0.0704408:  12%|█▎        | 5/40 [00:55<06:17, 10.78s/it]

[I 2025-11-25 14:20:16,745] Trial 4 finished with value: -0.07044080759091272 and parameters: {'n_estimators': 450, 'learning_rate': 0.014643894422299762, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7623538714083906, 'colsample_bytree': 0.9481119782739507, 'gamma': 2.279522844033547, 'reg_alpha': 1.223386627188852, 'reg_lambda': 0.10378492661299106}. Best is trial 4 with value: -0.07044080759091272.

Best trial: 4. Best value: -0.0704408:  15%|█▌        | 6/40 [00:58<04:40,  8.26s/it]

[I 2025-11-25 14:20:20,102] Trial 5 pruned.

Best trial: 4. Best value: -0.0704408:  18%|█▊        | 7/40 [01:21<07:07, 12.95s/it]

[I 2025-11-25 14:20:42,715] Trial 6 finished with value: -0.1098600026062347 and parameters: {'n_estimators': 839, 'learning_rate': 0.023375644593404365, 'max_depth': 11, 'min_child_weight': 5, 'subsample': 0.815467521706887, 'colsample_bytree': 0.7050093364930091, 'gamma': 4.295515860786389, 'reg_alpha': 0.3912561417209064, 'reg_lambda': 2.5526544148949792}. Best is trial 4 with value: -0.07044080759091272.

Best trial: 7. Best value: 0.0111063:  20%|██        | 8/40 [01:26<05:34, 10.46s/it]

[I 2025-11-25 14:20:47,832] Trial 7 finished with value: 0.011106311080308018 and parameters: {'n_estimators': 415, 'learning_rate': 0.010623610217812942, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.6814827938269733, 'colsample_bytree': 0.6545804133018197, 'gamma': 3.332060749158567, 'reg_alpha': 2.2050235944871517, 'reg_lambda': 1.0697925535421349}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  22%|██▎       | 9/40 [01:28<04:06,  7.94s/it]

[I 2025-11-25 14:20:50,232] Trial 8 pruned.

Best trial: 7. Best value: 0.0111063:  25%|██▌       | 10/40 [01:49<05:57, 11.90s/it]

[I 2025-11-25 14:21:11,021] Trial 9 pruned.

Best trial: 7. Best value: 0.0111063:  28%|██▊       | 11/40 [01:56<05:02, 10.43s/it]

[I 2025-11-25 14:21:18,105] Trial 10 finished with value: 0.007385780146176153 and parameters: {'n_estimators': 321, 'learning_rate': 0.01068472127525524, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.6135940645167369, 'colsample_bytree': 0.601958959064383, 'gamma': 0.06704253280744865, 'reg_alpha': 2.9433035731819066, 'reg_lambda': 0.1979843804000525}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  30%|███       | 12/40 [02:03<04:20,  9.29s/it]

[I 2025-11-25 14:21:24,801] Trial 11 finished with value: 0.007052399253244264 and parameters: {'n_estimators': 334, 'learning_rate': 0.010436830243805744, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.6233727043439056, 'colsample_bytree': 0.6015949698094893, 'gamma': 0.3273630392608946, 'reg_alpha': 2.685504543308772, 'reg_lambda': 0.1670095189244146}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  32%|███▎      | 13/40 [02:05<03:16,  7.30s/it]

[I 2025-11-25 14:21:27,499] Trial 12 pruned.

Best trial: 7. Best value: 0.0111063:  35%|███▌      | 14/40 [02:15<03:24,  7.88s/it]

[I 2025-11-25 14:21:36,719] Trial 13 finished with value: -0.007017270561419986 and parameters: {'n_estimators': 527, 'learning_rate': 0.011927775770401411, 'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.6899700853218339, 'colsample_bytree': 0.6737146340407845, 'gamma': 0.4060492589331638, 'reg_alpha': 2.096366514945239, 'reg_lambda': 1.337574094935611}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  38%|███▊      | 15/40 [02:28<03:57,  9.52s/it]

[I 2025-11-25 14:21:50,034] Trial 14 finished with value: -0.03333732939442199 and parameters: {'n_estimators': 344, 'learning_rate': 0.020580766546836483, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.6894386423993288, 'colsample_bytree': 0.6045270890971873, 'gamma': 1.6783325640872593, 'reg_alpha': 2.2730136159924106, 'reg_lambda': 0.5967099725473571}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  40%|████      | 16/40 [02:33<03:12,  8.03s/it]

[I 2025-11-25 14:21:54,597] Trial 15 pruned.

Best trial: 7. Best value: 0.0111063:  42%|████▎     | 17/40 [02:38<02:43,  7.12s/it]

[I 2025-11-25 14:21:59,601] Trial 16 pruned.

Best trial: 7. Best value: 0.0111063:  45%|████▌     | 18/40 [02:46<02:44,  7.48s/it]

[I 2025-11-25 14:22:07,922] Trial 17 finished with value: -0.013450417359542074 and parameters: {'n_estimators': 341, 'learning_rate': 0.01751726183795996, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.7282920139418546, 'colsample_bytree': 0.7119817275670383, 'gamma': 4.906396902806574, 'reg_alpha': 1.7868815889825242, 'reg_lambda': 1.1111476553751574}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  48%|████▊     | 19/40 [02:48<02:02,  5.81s/it]

[I 2025-11-25 14:22:09,846] Trial 18 pruned.

Best trial: 7. Best value: 0.0111063:  50%|█████     | 20/40 [02:55<02:05,  6.28s/it]

[I 2025-11-25 14:22:17,217] Trial 19 pruned.

Best trial: 7. Best value: 0.0111063:  52%|█████▎    | 21/40 [03:02<02:05,  6.58s/it]

[I 2025-11-25 14:22:24,496] Trial 20 finished with value: -0.02431021502098189 and parameters: {'n_estimators': 670, 'learning_rate': 0.013553184226330792, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.6571727074912851, 'colsample_bytree': 0.6314286362835256, 'gamma': 0.9159149617307394, 'reg_alpha': 1.758420746138551, 'reg_lambda': 0.2286129042523048}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  55%|█████▌    | 22/40 [03:10<02:02,  6.83s/it]

[I 2025-11-25 14:22:31,895] Trial 21 finished with value: 0.007448464090191102 and parameters: {'n_estimators': 348, 'learning_rate': 0.010107758104885992, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.6228019274639819, 'colsample_bytree': 0.6024517576629624, 'gamma': 0.6086955999663091, 'reg_alpha': 2.643544512981167, 'reg_lambda': 0.3384263752812227}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  57%|█████▊    | 23/40 [03:18<02:03,  7.27s/it]

[I 2025-11-25 14:22:40,192] Trial 22 finished with value: -7.022966305151683e-05 and parameters: {'n_estimators': 423, 'learning_rate': 0.011167964153165996, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.6374742852439557, 'colsample_bytree': 0.6750660824736421, 'gamma': 0.780230266685397, 'reg_alpha': 2.3789696125145086, 'reg_lambda': 0.3246522986652086}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  60%|██████    | 24/40 [03:22<01:38,  6.13s/it]

[I 2025-11-25 14:22:43,675] Trial 23 pruned.

Best trial: 7. Best value: 0.0111063:  62%|██████▎   | 25/40 [03:33<01:54,  7.63s/it]

[I 2025-11-25 14:22:54,797] Trial 24 finished with value: -0.006763570627284017 and parameters: {'n_estimators': 302, 'learning_rate': 0.010097480478359865, 'max_depth': 10, 'min_child_weight': 6, 'subsample': 0.8589408460534843, 'colsample_bytree': 0.66869008527104, 'gamma': 0.7185657126172301, 'reg_alpha': 2.777126169687354, 'reg_lambda': 0.3870926758149764}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  65%|██████▌   | 26/40 [03:36<01:27,  6.24s/it]

[I 2025-11-25 14:22:57,800] Trial 25 pruned.

Best trial: 7. Best value: 0.0111063:  68%|██████▊   | 27/40 [03:41<01:18,  6.06s/it]

[I 2025-11-25 14:23:03,455] Trial 26 pruned.

Best trial: 7. Best value: 0.0111063:  70%|███████   | 28/40 [03:43<00:58,  4.87s/it]

[I 2025-11-25 14:23:05,526] Trial 27 pruned.

Best trial: 7. Best value: 0.0111063:  72%|███████▎  | 29/40 [03:47<00:50,  4.56s/it]

[I 2025-11-25 14:23:09,384] Trial 28 pruned.

Best trial: 7. Best value: 0.0111063:  75%|███████▌  | 30/40 [03:52<00:46,  4.61s/it]

[I 2025-11-25 14:23:14,105] Trial 29 finished with value: -0.0003449863602084102 and parameters: {'n_estimators': 300, 'learning_rate': 0.01725333871128399, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6426093658048986, 'colsample_bytree': 0.6327007467037817, 'gamma': 2.6023166759034577, 'reg_alpha': 2.576715021333814, 'reg_lambda': 2.968585922544941}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  78%|███████▊  | 31/40 [04:15<01:30, 10.05s/it]

[I 2025-11-25 14:23:36,855] Trial 30 pruned.

Best trial: 7. Best value: 0.0111063:  80%|████████  | 32/40 [04:23<01:14,  9.36s/it]

[I 2025-11-25 14:23:44,594] Trial 31 finished with value: 0.004121829491231632 and parameters: {'n_estimators': 392, 'learning_rate': 0.010276088493285691, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.6242276838746821, 'colsample_bytree': 0.6020126574377873, 'gamma': 0.3763688854920024, 'reg_alpha': 2.7083046502374475, 'reg_lambda': 0.19341003522337297}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  82%|████████▎ | 33/40 [04:25<00:51,  7.37s/it]

[I 2025-11-25 14:23:47,308] Trial 32 pruned.

Best trial: 7. Best value: 0.0111063:  85%|████████▌ | 34/40 [04:29<00:38,  6.42s/it]

[I 2025-11-25 14:23:51,525] Trial 33 finished with value: 0.007076537313651321 and parameters: {'n_estimators': 370, 'learning_rate': 0.01240587731413549, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.646622803481964, 'colsample_bytree': 0.6564711929141281, 'gamma': 0.6006484903136885, 'reg_alpha': 2.2193882721516465, 'reg_lambda': 0.3313093710477846}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  88%|████████▊ | 35/40 [04:35<00:30,  6.01s/it]

[I 2025-11-25 14:23:56,591] Trial 34 finished with value: 0.00584041835574467 and parameters: {'n_estimators': 385, 'learning_rate': 0.012672039893755371, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.7161785120554414, 'colsample_bytree': 0.654671273983988, 'gamma': 0.6451379490043341, 'reg_alpha': 2.2126212066571203, 'reg_lambda': 0.40718989779972103}. Best is trial 7 with value: 0.011106311080308018.

Best trial: 7. Best value: 0.0111063:  90%|█████████ | 36/40 [04:37<00:19,  4.83s/it]

[I 2025-11-25 14:23:58,651] Trial 35 pruned.

Best trial: 7. Best value: 0.0111063:  92%|█████████▎| 37/40 [04:40<00:13,  4.35s/it]

[I 2025-11-25 14:24:01,891] Trial 36 pruned.

Best trial: 7. Best value: 0.0111063:  95%|█████████▌| 38/40 [04:42<00:07,  3.55s/it]

[I 2025-11-25 14:24:03,564] Trial 37 pruned.

Best trial: 7. Best value: 0.0111063:  98%|█████████▊| 39/40 [04:45<00:03,  3.53s/it]

[I 2025-11-25 14:24:07,047] Trial 38 pruned.

Best trial: 7. Best value: 0.0111063: 100%|██████████| 40/40 [04:48<00:00,  7.21s/it]

[I 2025-11-25 14:24:09,858] Trial 39 pruned.

✓ Tuning complete!
Best R²: 0.0111

Best Parameters:
  n_estimators: 415
  learning_rate: 0.010623610217812942
  max_depth: 5
  min_child_weight: 8
  subsample: 0.6814827938269733
  colsample_bytree: 0.6545804133018197
  gamma: 3.332060749158567
  reg_alpha: 2.2050235944871517
  reg_lambda: 1.0697925535421349

============================================================
TRAINING FINAL MODEL
============================================================
Train size: 71820
Validation size: 17955

Training model...
FINAL MODEL METRICS

Training Set:
  R²:     0.2552
  MAPE:   8290039265206894592.00%
  MdAPE:  15.00%

Validation Set:
  R²:     0.0062
  MAPE:   34.48%
  MdAPE:  14.90%

Overfitting Check:
  R² difference: 0.2490
  ⚠️  Significant overfitting detected
TEST SET EVALUATION

Test Set Metrics:
  R²:     -1.3866
  MAPE:   37.89%
  MdAPE:  15.88%

============================================================
SAVING ARTIFACTS
============================================================
✓ Model saved: xgb_final_model.pkl
✓ Parameters saved: best_params.pkl
✓ Predictions saved: test_predictions.csv
✓ Metrics saved: model_metrics.csv

============================================================
PIPELINE COMPLETE!
============================================================